sudo: true
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '12'
  - '14'
  - '15'

script:
  - npm run test
  - npm run test:with-setup
after_success:
  - codecov
branches:
  only:
    - master